apiVersion: v1
kind: Service
metadata:
  name: ui-api
  labels:
    app: ui-api
spec:
  type: LoadBalancer
  selector:
    app: ui-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
