apiVersion: v1
kind: Service
metadata:
  name: ui-api
  labels:
    app: ui-api
spec:
  type: LoadBalancer
  selector:
    app: ui-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: ui-api
    servicePort: 80
  rules:
  - host: dataseams.local
    http:
      paths:
      - path: /
        backend:
          serviceName: ui-api
          servicePort: 80
