apiVersion: v1
kind: Service
metadata:
  name: ui-api
  labels:
    app: ui-api
spec:
  type: NodePort
  selector:
    app: ui-api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
