version: "3.7"
services:
  postgres-api:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "detours"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "sam"
      POSTGRES_PASSWORD: "abcd"
    networks:
      detours:
        aliases:
          - postgres-api

networks:
  detours:
