version: "3.7"
services:
  postgres-api:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "detours"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "sam"
      POSTGRES_PASSWORD: "abcd"
    networks:
      detours:
        aliases:
          - postgres-api
  core-api:
    build: ./core-api
    image: detours/core-api
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: postgres-api
      POSTGRES_PORT: 5432
      POSTGRES_DB: detours
      POSTGRES_USER: sam
      POSTGRES_PASSWORD: abcd
    networks:
      detours:
        aliases:
          - core-api
    depends_on:
      - "postgres-api"

networks:
  detours:
