version: "3.7"
services:
  postgres:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      detours:
        aliases:
          - postgres
  core:
    build: ./core
    image: detours/core
    ports:
      - 5000:5000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZOMATO_API_KEY: ${ZOMATO_API_KEY}
      ZOMATO_API_URL: ${ZOMATO_API_URL}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    networks:
      detours:
        aliases:
          - core
    depends_on:
      - postgres
  ui:
    build:
      context: ./ui
      args:
        NODE_ENV: production
    image: detours/ui
    ports:
      - 3000:3000
    env_file:
      - ./ui/app/.env.gcp
    networks:
      detours:
        aliases:
          - ui
    depends_on:
      - core

networks:
  detours:
