[tool.black]
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | \.venv
    | \.pytest_cache
    | __pycache__
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.coverage.run]
omit = ['*tests/*']

[tool.isort]
profile = "black"
line_length = 79
