apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: detours-dev

profiles:
- name: core
  build:
    artifacts:
    - image: detours/core
      context: core/.
      sync:
        manual:
        - src: "core/*"
          dest: "app/"
      docker:
        dockerfile: dockerfile
  deploy:
    kubectl:
      manifests:
      - k8s/minikube/core/deployment.yml
      - k8s/minikube/core/service.yml
      - k8s/minikube/core/ingress.yml
      flags:
        global: [-n,development]
- name: ui
  build:
    artifacts:
    - image: detours/ui
      context: ui/.
      sync:
        manual:
        - src: "ui/*"
          dest: "app/"
      docker:
        dockerfile: dockerfile
  deploy:
    kubectl:
      manifests:
      - k8s/minikube/ui/secret.yml
      - k8s/minikube/ui/deployment.yml
      - k8s/minikube/ui/service.yml
      - k8s/minikube/ui/ingress.yml
      flags:
        global: [-n,development]
- name: postgres
  deploy:
    kubectl:
      manifests:
      - k8s/minikube/postgres/configmap.yml
      - k8s/minikube/postgres/secret.yml
      - k8s/minikube/postgres/pv.yml
      - k8s/minikube/postgres/pvc.yml
      - k8s/minikube/postgres/deployment.yml
      - k8s/minikube/postgres/service.yml
      flags:
        global: [-n,development]
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: detours/core
    context: core/.
    sync:
      manual:
      - src: "core/*"
        dest: "app/"
    docker:
      dockerfile: dockerfile
  - image: detours/ui
    context: ui/.
    sync:
      manual:
      - src: "ui/*"
        dest: "app/"
    docker:
      dockerfile: dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/minikube/postgres/configmap.yml
    - k8s/minikube/postgres/secret.yml
    - k8s/minikube/postgres/pv.yml
    - k8s/minikube/postgres/pvc.yml
    - k8s/minikube/postgres/deployment.yml
    - k8s/minikube/postgres/service.yml
    - k8s/minikube/core/deployment.yml
    - k8s/minikube/core/service.yml
    - k8s/minikube/core/ingress.yml
    - k8s/minikube/ui/secret.yml
    - k8s/minikube/ui/deployment.yml
    - k8s/minikube/ui/service.yml
    - k8s/minikube/ui/ingress.yml
    flags:
      global: [-n,development]
