apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: detours-dev

profiles:
- name: core-api
  build:
    artifacts:
    - image: detours/core-api
      context: core-api/.
      sync:
        manual:
        - src: "core-api/*"
          dest: "app/"
      docker:
        dockerfile: dockerfile
  deploy:
    kubectl:
      manifests:
      - k8s/minikube/core-api/deployment.yml
      - k8s/minikube/core-api/service.yml
      - k8s/minikube/core-api/ingress.yml
      flags:
        global: [-n,development]
- name: ui-api
  build:
    artifacts:
    - image: detours/ui-api
      context: ui-api/.
      sync:
        manual:
        - src: "ui-api/*"
          dest: "app/"
      docker:
        dockerfile: dockerfile
  deploy:
    kubectl:
      manifests:
      - k8s/minikube/ui-api/secret.yml
      - k8s/minikube/ui-api/deployment.yml
      - k8s/minikube/ui-api/service.yml
      - k8s/minikube/ui-api/ingress.yml
      flags:
        global: [-n,development]
- name: postgres-api
  deploy:
    kubectl:
      manifests:
      - k8s/minikube/postgres/configmap.yml
      - k8s/minikube/postgres-api/secret.yml
      - k8s/minikube/postgres-api/pv.yml
      - k8s/minikube/postgres-api/pvc.yml
      - k8s/minikube/postgres-api/deployment.yml
      - k8s/minikube/postgres-api/service.yml
      flags:
        global: [-n,development]
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: detours/core-api
    context: core-api/.
    sync:
      manual:
      - src: "core-api/*"
        dest: "app/"
    docker:
      dockerfile: dockerfile
  - image: detours/ui-api
    context: ui-api/.
    sync:
      manual:
      - src: "ui-api/*"
        dest: "app/"
    docker:
      dockerfile: dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/minikube/postgres-api/configmap.yml
    - k8s/minikube/postgres-api/secret.yml
    - k8s/minikube/postgres-api/pv.yml
    - k8s/minikube/postgres-api/pvc.yml
    - k8s/minikube/postgres-api/deployment.yml
    - k8s/minikube/postgres-api/service.yml
    - k8s/minikube/core-api/deployment.yml
    - k8s/minikube/core-api/service.yml
    - k8s/minikube/core-api/ingress.yml
    - k8s/minikube/ui-api/secret.yml
    - k8s/minikube/ui-api/deployment.yml
    - k8s/minikube/ui-api/service.yml
    - k8s/minikube/ui-api/ingress.yml
    flags:
      global: [-n,development]
