kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-api
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-api
