apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5432
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: postgres-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: postgres-service
    servicePort: 80
  rules:
  - host: dataseams.local
    http:
      paths:
      - path: /postgres/*
        backend:
          serviceName: postgres-service
          servicePort: 80
