FROM python:3.8.1-alpine3.11

RUN apk add build-base \
            postgresql-dev

RUN mkdir /app
WORKDIR /app

COPY . /app/

RUN pip install -r requirements.txt

ENV FLASK_APP=/app/core/src_sql/app.py

CMD ["gunicorn", "--bind=:5000", "--timeout=300", "app:app"]
