name: detours
channels:
  - defaults
dependencies:
  - pip
  - python=3.8
  - pip:
    - flake8==3.7.9
    - flake8-docstrings==1.5.0
    - pep8-naming==0.9.1
    - black==19.10b0
    - flask==1.1.1
    - flask-graphql==2.0.1
    - gunicorn==20.0.4
    - graphene==2.1.8
    - graphene-sqlalchemy==2.2.2
    - pytest==5.3.4
    - pytest-benchmark==3.2.3
    - pytest-asyncio==0.10.0
    - pytest-cov==2.8.1
    - coveralls==1.10.0
    - snapshottest==0.5.1
    - promise==2.3
    - pytz==2019.3
    - psycopg2==2.8.4
