apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
data:
  CORE_API_URL: "https://graphql.dataseams.com/graphql"
  NODE_ENV: "production"
  LOGIN_API_URL: "https://app.dataseams.com/api/login"
  LOGOUT_API_URL: "https://app.dataseams.com/api/logout"
  STRIPE_REDIRECT_TO_HOST: "https://app.dataseams.com"
