apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: gcr.io/robocation/ui:latest
        imagePullPolicy: Always
        env:
          - name: GOOGLE_MAPS_API_KEY
            valueFrom:
              secretKeyRef:
                name: google
                key: GOOGLE_MAPS_API_KEY
          - name: CORE_API_URL
            valueFrom:
                configMapKeyRef:
                  name: ui
                  key: CORE_API_URL
          - name: NODE_ENV
            valueFrom:
                configMapKeyRef:
                  name: ui
                  key: NODE_ENV
          - name: LOGIN_API_URL
            valueFrom:
              configMapKeyRef:
                name: ui
                key: LOGIN_API_URL
          - name: LOGOUT_API_URL
            valueFrom:
              configMapKeyRef:
                name: ui
                key: LOGOUT_API_URL
        ports:
          - name: ui
            containerPort: 3000
            protocol: TCP
        resources:
          requests:
            memory: "1G"
            cpu: "1"
          limits:
            memory: "1G"
            cpu: "1"
