"""Add attrition feedback table.

Revision ID: 984495681587
Revises: 55505d30293b
Create Date: 2021-10-02 22:05:03.745863

"""
import sqlalchemy as sa
from alembic import context, op


# revision identifiers, used by Alembic.
revision = "984495681587"
down_revision = "55505d30293b"
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade database."""
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def downgrade():
    """Downgrade database."""
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attrition_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("incognito_id", sa.String(length=100), nullable=False),
        sa.Column("reason_for_leaving", sa.Integer(), nullable=True),
        sa.Column("improvement", sa.String(length=4000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attrition_feedback")
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here."""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here."""
    pass
