"""add spending_per_day for cities

Revision ID: aef1438b238a
Revises: 50478441c45c
Create Date: 2021-07-18 17:46:34.180352

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aef1438b238a"
down_revision = "50478441c45c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "city", sa.Column("spending_per_day", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("city", "spending_per_day")
    # ### end Alembic commands ###
