FROM python:3.8.1-slim-buster

RUN apt update && apt install -y \
    build-essential \
    libpq-dev

RUN mkdir /app /app/core_api /app/tests
WORKDIR /app

COPY environment.yml requirements.py /app/
RUN pip install $(python -c "import requirements; print(requirements.get_ssv(['#prod']))")

COPY core_api /app/core_api/
COPY tests /app/tests/
COPY app.py Makefile README.md setup.py wait-for-it.sh /app/

ENV FLASK_APP=/app/app.py

RUN chmod 550 wait-for-it.sh

CMD ["gunicorn", "--bind=:5000", "--timeout=300", "app:app"]
