FROM python:3.8.1-alpine3.11

RUN apk update && apk upgrade && \
    apk add build-base \
        postgresql-dev

RUN mkdir /app
WORKDIR /app

COPY . /app/

RUN pip install -r requirements.txt && \
    pip install .

ENV FLASK_APP=/app/core/src_sql/app.py \
    POSTGRES_USER=sam \
    POSTGRES_PASSWORD=myP@$s \
    POSTGRES_HOST=postgres-service \
    POSTGRES_PORT=5432 \
    POSTGRES_DB=detours

CMD gunicorn --bind 0.0.0.0:5000 core.app:app
