name: detours
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic=1.6.4 #prod
  - beautifulsoup4=4.9.3 #dev
  - black=19.10b0 #dev
  - coveralls=3.1.0 #dev
  - flake8-docstrings=1.6.0 #dev
  - flake8=3.9.2 #dev
  - flask-cors=3.0.10 #prod
  - flask-graphql=2.0.1 #prod
  - flask=1.1.2 #prod
  - graphene-sqlalchemy=2.3.0 #prod
  - graphene=2.1.8 #prod
  - gunicorn=20.1.0 #prod
  - isort=5.8.0 #dev
  - jupyterlab=3.0.14 #dev
  - pandas=1.2.4 #prod
  - pep8-naming=0.8.2 #dev
  - pip=21.1.2
  - promise=2.3 #prod
  - psycopg2=2.8.6 #prod
  - pytest-asyncio=0.15.1 #dev
  - pytest-benchmark=3.4.1 #dev
  - pytest-cov=2.11.1 #dev
  - pytest=6.2.4 #dev
  - python=3.9.5
  - pytz=2021.1 #prod
  - pyyaml=5.4.1 #dev
  - requests=2.25.1 #prod
  - rope=0.19.0 #prod
  - snapshottest=0.5.1 #dev
  - wordcloud=1.8.1 #dev
  - stripe=2.49.0 #prod
