name: detours
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic=1.7.5 #prod
  - beautifulsoup4=4.10.0 #dev
  - black=19.10b0 #dev
  - coveralls=3.2.0 #dev
  - flake8-docstrings=1.6.0 #dev
  - flake8=4.0.1 #dev
  - flask-cors=3.0.10 #prod
  - flask-graphql=2.0.1 #prod
  - flask=2.0.2 #prod
  - graphene-sqlalchemy=2.3.0 #prod
  - graphene=2.1.9 #prod
  - gunicorn=20.1.0 #prod
  - isort=5.9.3 #dev
  - jupyterlab=3.2.9 #dev
  - pandas=1.4.1 #prod
  - pep8-naming=0.12.1 #dev
  - pip=21.2.4
  - promise=2.3 #prod
  - psycopg2=2.8.6 #prod
  - pytest-asyncio=0.16.0 #dev
  - pytest-benchmark=3.4.1 #dev
  - pytest-cov=3.0.0 #dev
  - pytest=6.2.5 #dev
  - python=3.9.7
  - pytz=2021.3 #prod
  - pyyaml=6.0 #dev
  - requests=2.27.1 #prod
  - rope=0.22.0 #prod
  - snapshottest=0.5.1 #dev
  - wordcloud=1.8.1 #dev
  - stripe=2.49.0 #prod
