apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
