apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- core/configmap.yml
- core/service-account.yml
- core/deployment.yml
- core/service.yml
- ui/configmap.yml
- ui/deployment.yml
- ui/service.yml
- managed-certificate.yml
- ingress.yml
