apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- core/configmap.yml
- core/pod.yml
- core/service.yml
- ui/configmap.yml
- ui/deployment.yml
- ui/service.yml
