- name: environment setup
  hosts: localhost
  tasks:

# ui package requirements
  - name: download nodejs and npm
    get_url:
      url: https://deb.nodesource.com/setup_12.x
      dest: /tmp/nodesetup
      mode: '0755'

  - name: setup nodejs and npm
    become: true
    command: /tmp/nodesetup

  - name: install nodejs
    become: true
    apt:
      name: nodejs
      state: latest

  - name: install gcc
    become: true
    apt:
      name: gcc
      state: latest

  - name: install g++
    become: true
    apt:
      name: g++
      state: latest

  - name: install make
    become: true
    apt:
      name: make
      state: latest

# Minikube and infrastructure
  - name: download minikube
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      dest: /tmp/minikube
      mode: '0755'

  - name: setup minikube
    become: True
    command: install /tmp/minikube /usr/local/bin

  - name: download skaffold
    get_url:
      url: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
      dest: /tmp/skaffold
      mode: '0755'

  - name: setup skaffold
    become: true
    copy: remote_src=True src=/tmp/skaffold dest=/usr/local/bin/
