FROM python:3.8.1-alpine3.11

RUN apk add build-base \
    postgresql-dev \
    bash

RUN mkdir /app
WORKDIR /app

COPY . /app/

RUN pip install $(python -c "import requirements; print(requirements.get_ssv(['#prod']))")

ENV FLASK_APP=/app/core/src_sql/app.py

RUN chmod 550 wait-for-it.sh

CMD ["gunicorn", "--bind=:5000", "--timeout=300", "app:app"]
