apiVersion: v1
kind: Service
metadata:
  name: core
  labels:
    app: core
spec:
  type: NodePort
  selector:
    app: core
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
