apiVersion: v1
kind: Service
metadata:
  name: core
  labels:
    app: core
spec:
  type: LoadBalancer
  selector:
    app: core
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: core
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: core
    servicePort: 80
  rules:
  - host: dataseams.local
    http:
      paths:
      - path: /core/*
        backend:
          serviceName: core
          servicePort: 80
