apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: core
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: core
    servicePort: 5000
  rules:
  - host: graphql.dataseams.local
    http:
      paths:
      - path: /
        backend:
          serviceName: core
          servicePort: 5000
