apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "robocation-static-ip"
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
