apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
status:
  loadBalancer:
    ingress:
      - ip: 34.94.90.221
