FROM python:3.7-alpine3.8
RUN apk update && apk upgrade
RUN apk add curl

RUN mkdir /app
WORKDIR /app
COPY app.py requirements.txt /app/

RUN pip install -r requirements.txt

ENV CORE_SVC_IP core
ENV CORE_SVC_PORT 5000
ENV FLASK_APP=/app/app.py

CMD gunicorn --bind 0.0.0.0:8080 app:app
