FROM node:12.12.0-alpine

ARG NODE_ENV=production
ARG LOGIN_API_URL
ARG LOGOUT_API_URL
ARG CORE_API_URL
ARG REACT_APP_GOOGLE_MAPS_API_KEY
ARG STRIPE_PUBLIC_KEY
ENV LOGIN_API_URL=$LOGIN_API_URL \
    LOGOUT_API_URL=$LOGOUT_API_URL \
    CORE_API_URL=$CORE_API_URL \
    REACT_APP_GOOGLE_MAPS_API_KEY=$REACT_APP_GOOGLE_MAPS_API_KEY \
    STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY

WORKDIR /app
RUN mkdir pages components credentials src utils static redux
COPY app/.babelrc app/next.config.js app/package*.json app/server.js /app/
RUN npm install

COPY app/pages /app/pages/
COPY app/components /app/components/
COPY app/credentials /app/credentials/
COPY app/src /app/src/
COPY app/utils /app/utils/
COPY app/static /app/static/
COPY app/redux /app/redux/

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
