name: Source code checks

on: [pull_request]

jobs:
  code-lint:
    runs-on: ubuntu-latest
    name: code lint
    steps:
      - name: check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: run black checks
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "core/"
          use-pylint: false
          use-pycodestyle: false
          use-mypy: false
          use-flake8: false
          use-black: true
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""
  docstring-lint:
      runs-on: ubuntu-latest
      name: docstring lint
      steps:
        - name: Check out source repository
          uses: actions/checkout@v2
        - name: Set up Python environment
          uses: actions/setup-python@v1
          with:
            python-version: "3.8"
        - name: flake8 lint
          uses: py-actions/flake8@v1
          with:
            python-root-list: "core/"
            use-pycodestyle: false
            use-mypy: false
            use-flake8: true
            use-black: false
            extra-flake8-options: ""
