name: Source code checks

on: [pull_request]

jobs:
  black-format:
    runs-on: ubuntu-latest
    name: Code lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: black format
        uses: py-actions/flake8@v1
        with:
          python-root-list: "core/"
          use-pycodestyle: false
          use-mypy: false
          use-black: true
          extra-black-options: "--line-length=79"
  flake8-lint:
      runs-on: ubuntu-latest
      name: Docstring lint
      steps:
        - name: Check out source repository
          uses: actions/checkout@v2
        - name: Set up Python environment
          uses: actions/setup-python@v1
          with:
            python-version: "3.8"
        - name: flake8 lint
          uses: py-actions/flake8@v1
          with:
            python-root-list: "core/"
            use-pycodestyle: false
            use-mypy: false
            use-flake8: true
            extra-flake8-options: ""
