name: Unit tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install $(python -c "import requirements; print(requirements.get_ssv(['#prod', '#dev']))")
      working-directory: ./core
    - name: Run unit tests for core service
      run: python -m pytest
      working-directory: ./core
